/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_genus_ctp_impl_GenusCTPServerImpl */

#ifndef _Included_com_genus_ctp_impl_GenusCTPServerImpl
#define _Included_com_genus_ctp_impl_GenusCTPServerImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_genus_ctp_impl_GenusCTPServerImpl
 * Method:    StartCTPTradeServer
 * Signature: (Lcom/genus/ctp/callback/GenusCTPTradeCallback;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_genus_ctp_impl_GenusCTPServerImpl_StartCTPTradeServer
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     com_genus_ctp_impl_GenusCTPServerImpl
 * Method:    StartCTPMarketServer
 * Signature: (Lcom/genus/ctp/callback/GenusCTPMarketDataCallback;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_genus_ctp_impl_GenusCTPServerImpl_StartCTPMarketServer
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     com_genus_ctp_impl_GenusCTPServerImpl
 * Method:    StopCTPServer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_genus_ctp_impl_GenusCTPServerImpl_StopCTPServer
  (JNIEnv *, jobject);

/*
 * Class:     com_genus_ctp_impl_GenusCTPServerImpl
 * Method:    GetApiVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_genus_ctp_impl_GenusCTPServerImpl_GetApiVersion
  (JNIEnv *, jobject);

/*
 * Class:     com_genus_ctp_impl_GenusCTPServerImpl
 * Method:    GetTradingDay
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_genus_ctp_impl_GenusCTPServerImpl_GetTradingDay
  (JNIEnv *, jobject);

/*
 * Class:     com_genus_ctp_impl_GenusCTPServerImpl
 * Method:    ReqTradeAuthenticate
 * Signature: (Lcom/genus/ctp/mode/GenusCTPReqAuthenticateField;I)I
 */
JNIEXPORT jint JNICALL Java_com_genus_ctp_impl_GenusCTPServerImpl_ReqTradeAuthenticate
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_genus_ctp_impl_GenusCTPServerImpl
 * Method:    ReqMarketDataAuthenticate
 * Signature: (Lcom/genus/ctp/mode/GenusCTPReqAuthenticateField;I)I
 */
JNIEXPORT jint JNICALL Java_com_genus_ctp_impl_GenusCTPServerImpl_ReqMarketDataAuthenticate
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_genus_ctp_impl_GenusCTPServerImpl
 * Method:    ReqTradeUserLogin
 * Signature: (Lcom/genus/ctp/mode/GenusCTPReqUserLoginField;I)I
 */
JNIEXPORT jint JNICALL Java_com_genus_ctp_impl_GenusCTPServerImpl_ReqTradeUserLogin
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_genus_ctp_impl_GenusCTPServerImpl
 * Method:    ReqMarketDataUserLogin
 * Signature: (Lcom/genus/ctp/mode/GenusCTPReqUserLoginField;I)I
 */
JNIEXPORT jint JNICALL Java_com_genus_ctp_impl_GenusCTPServerImpl_ReqMarketDataUserLogin
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_genus_ctp_impl_GenusCTPServerImpl
 * Method:    ReqTradeUserLogout
 * Signature: (Lcom/genus/ctp/mode/GenusCTPReqUserLogoutField;I)I
 */
JNIEXPORT jint JNICALL Java_com_genus_ctp_impl_GenusCTPServerImpl_ReqTradeUserLogout
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_genus_ctp_impl_GenusCTPServerImpl
 * Method:    ReqMarketDataUserLogout
 * Signature: (Lcom/genus/ctp/mode/GenusCTPReqUserLogoutField;I)I
 */
JNIEXPORT jint JNICALL Java_com_genus_ctp_impl_GenusCTPServerImpl_ReqMarketDataUserLogout
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_genus_ctp_impl_GenusCTPServerImpl
 * Method:    ReqQryInstrument
 * Signature: (Lcom/genus/ctp/mode/GenusCTPQryInstrumentField;I)I
 */
JNIEXPORT jint JNICALL Java_com_genus_ctp_impl_GenusCTPServerImpl_ReqQryInstrument
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_genus_ctp_impl_GenusCTPServerImpl
 * Method:    ReqQryDepthMarketData
 * Signature: (Lcom/genus/ctp/mode/GenusCTPQryDepthMarketDataField;I)I
 */
JNIEXPORT jint JNICALL Java_com_genus_ctp_impl_GenusCTPServerImpl_ReqQryDepthMarketData
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_genus_ctp_impl_GenusCTPServerImpl
 * Method:    SubscribeMarketData
 * Signature: (Ljava/util/List;I)I
 */
JNIEXPORT jint JNICALL Java_com_genus_ctp_impl_GenusCTPServerImpl_SubscribeMarketData
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_genus_ctp_impl_GenusCTPServerImpl
 * Method:    UnSubscribeMarketData
 * Signature: (Ljava/util/List;I)I
 */
JNIEXPORT jint JNICALL Java_com_genus_ctp_impl_GenusCTPServerImpl_UnSubscribeMarketData
  (JNIEnv *, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
