/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_genus_ctp_impl_GenusCTPServerImpl */

#ifndef _Included_com_genus_ctp_impl_GenusCTPServerImpl
#define _Included_com_genus_ctp_impl_GenusCTPServerImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_genus_ctp_impl_GenusCTPServerImpl
 * Method:    StartCTPTradeServer
 * Signature: (Lcom/genus/ctp/GenusCTPTradeCallback;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_genus_ctp_impl_GenusCTPServerImpl_StartCTPTradeServer
	(JNIEnv* pEnv, jobject obj, jobject tradeSpi, jstring tradeFontAddr);

/*
 * Class:     com_genus_ctp_impl_GenusCTPServerImpl
 * Method:    StartCTPMarketServer
 * Signature: (Lcom/genus/ctp/GenusCTPMarketDataCallback;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_genus_ctp_impl_GenusCTPServerImpl_StartCTPMarketServer
(JNIEnv* pEnv, jobject obj, jobject marketSpi,  jstring marketFontAddr);


/*
 * Class:     com_genus_ctp_impl_GenusCTPServerImpl
 * Method:    StopCTPServer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_genus_ctp_impl_GenusCTPServerImpl_StopCTPServer
(JNIEnv* pEnv, jobject obj);


/*
 * Class:     com_genus_ctp_impl_GenusCTPServerImpl
 * Method:    GetApiVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_genus_ctp_impl_GenusCTPServerImpl_GetApiVersion
(JNIEnv* pEnv, jobject obj);

/*
 * Class:     com_genus_ctp_impl_GenusCTPServerImpl
 * Method:    GetTradingDay
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_genus_ctp_impl_GenusCTPServerImpl_GetTradingDay
(JNIEnv* pEnv, jobject obj);

/*
 * Class:     com_genus_ctp_impl_GenusCTPServerImpl
 * Method:    ReqAuthenticate
 * Signature: (Lcom/genus/ctp/mode/GenusCTPReqAuthenticateField;I)I
 */
JNIEXPORT jint JNICALL Java_com_genus_ctp_impl_GenusCTPServerImpl_ReqTradeAuthenticate
(JNIEnv* pEnv, jobject obj, jobject reqAuthenticate, jint nRequestID);

/*
 * Class:     com_genus_ctp_impl_GenusCTPServerImpl
 * Method:    ReqAuthenticate
 * Signature: (Lcom/genus/ctp/mode/GenusCTPReqAuthenticateField;I)I
 */
JNIEXPORT jint JNICALL Java_com_genus_ctp_impl_GenusCTPServerImpl_ReqMarketDataAuthenticate
(JNIEnv* pEnv, jobject obj, jobject reqAuthenticate, jint nRequestID);

/*
 * Class:     com_genus_ctp_impl_GenusCTPServerImpl
 * Method:    ReqUserLogin
 * Signature: (Lcom/genus/ctp/mode/GenusCTPReqUserLoginField;I)I
 */
JNIEXPORT jint JNICALL Java_com_genus_ctp_impl_GenusCTPServerImpl_ReqTradeUserLogin
(JNIEnv* pEnv, jobject obj, jobject reqUserLogin, jint nRequestID);
/*
 * Class:     com_genus_ctp_impl_GenusCTPServerImpl
 * Method:    ReqUserLogin
 * Signature: (Lcom/genus/ctp/mode/GenusCTPReqUserLoginField;I)I
 */
JNIEXPORT jint JNICALL Java_com_genus_ctp_impl_GenusCTPServerImpl_ReqMarketDataUserLogin
(JNIEnv* pEnv, jobject obj, jobject reqUserLogin, jint nRequestID);

/*
 * Class:     com_genus_ctp_impl_GenusCTPServerImpl
 * Method:    ReqUserLogout
 * Signature: (Lcom/genus/ctp/mode/GenusCTPReqUserLogoutField;I)I
 */
JNIEXPORT jint JNICALL Java_com_genus_ctp_impl_GenusCTPServerImpl_ReqTradeUserLogout
(JNIEnv* pEnv, jobject obj, jobject reqUserLogout, jint nRequestID);

/*/*
 * Class:     com_genus_ctp_impl_GenusCTPServerImpl
 * Method:    ReqUserLogout
 * Signature: (Lcom/genus/ctp/mode/GenusCTPReqUserLogoutField;I)I
 */
JNIEXPORT jint JNICALL Java_com_genus_ctp_impl_GenusCTPServerImpl_ReqMarketDataUserLogout
(JNIEnv* pEnv, jobject obj, jobject reqUserLogout, jint nRequestID);

/*
 * Class:     com_genus_ctp_impl_GenusCTPServerImpl
 * Method:    ReqQryInstrument
 * Signature: (Lcom/genus/ctp/mode/GenusCTPQryInstrumentField;I)I
 */
JNIEXPORT jint JNICALL Java_com_genus_ctp_impl_GenusCTPServerImpl_ReqQryInstrument
(JNIEnv* pEnv, jobject obj, jobject qryInstrumentField, jint nRequestID);

/*
 * Class:     com_genus_ctp_impl_GenusCTPServerImpl
 * Method:    ReqQryDepthMarketData
 * Signature: (Lcom/genus/ctp/mode/GenusCTPQryDepthMarketDataField;I)I
 */
JNIEXPORT jint JNICALL Java_com_genus_ctp_impl_GenusCTPServerImpl_ReqQryDepthMarketData
(JNIEnv* pEnv, jobject obj, jobject qryDepthMarketData, jint nRequestID);

/*
 * Class:     com_genus_ctp_impl_GenusCTPServerImpl
 * Method:    SubscribeMarketData
 * Signature: (Ljava/util/List;I)I
 */
JNIEXPORT jint JNICALL Java_com_genus_ctp_impl_GenusCTPServerImpl_SubscribeMarketData
(JNIEnv* pEnv, jobject obj, jobject instrumentIDs, jint count);

/*
 * Class:     com_genus_ctp_impl_GenusCTPServerImpl
 * Method:    UnSubscribeMarketData
 * Signature: (Ljava/util/List;I)I
 */
JNIEXPORT jint JNICALL Java_com_genus_ctp_impl_GenusCTPServerImpl_UnSubscribeMarketData
(JNIEnv* pEnv, jobject obj, jobject instrumentIDs, jint count);

#ifdef __cplusplus
}
#endif
#endif
